import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { api } from '../services/api';
import './EventReportPage.css';

function EventReportPage() {
  const { eventId } = useParams();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    fetchReport();
  }, [eventId]);

  const fetchReport = async () => {
    try {
      const data = await api.getEventReport(eventId);
      setReport(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  const formatTime = (dateString) => {
    return new Date(dateString).toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const exportPDF = () => {
    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.text('PLANORA - Event Coordination Report', 14, 20);

    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('Event Information', 14, 35);

    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);

    const eventInfo = [
      ['Event Name:', report.event.name],
      ['Location:', report.event.location],
      ['Venue Size:', report.event.venue_size],
      ['Event Type:', report.event.event_type.charAt(0).toUpperCase() + report.event.event_type.slice(1)],
      ['Expected Attendees:', report.event.expected_attendees.toString()],
      ['Start Date & Time:', `${formatDate(report.event.start_date)} at ${formatTime(report.event.start_date)}`],
      ['End Date & Time:', `${formatDate(report.event.end_date)} at ${formatTime(report.event.end_date)}`],
      ['Duration:', report.summary.eventDuration],
      ['Status:', report.event.status.charAt(0).toUpperCase() + report.event.status.slice(1)]
    ];

    doc.autoTable({
      startY: 40,
      head: [],
      body: eventInfo,
      theme: 'plain',
      styles: { fontSize: 10 },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 50 },
        1: { cellWidth: 130 }
      }
    });

    let currentY = doc.lastAutoTable.finalY + 10;

    doc.setFont(undefined, 'bold');
    doc.setFontSize(12);
    doc.text('Waste Management', 14, currentY);
    currentY += 7;

    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    doc.text(`Estimated Waste Generation: ${Math.round(report.event.estimated_waste)} kg`, 14, currentY);
    currentY += 10;

    if (report.vendors && report.vendors.length > 0) {
      doc.setFont(undefined, 'bold');
      doc.setFontSize(12);
      doc.text('Registered Vendors', 14, currentY);
      currentY += 5;

      const vendorData = report.vendors.map(v => [
        v.name,
        v.category.charAt(0).toUpperCase() + v.category.slice(1),
        v.contact_email,
        v.contact_phone
      ]);

      doc.autoTable({
        startY: currentY,
        head: [['Vendor Name', 'Category', 'Email', 'Phone']],
        body: vendorData,
        theme: 'striped',
        styles: { fontSize: 9 },
        headStyles: { fillColor: [44, 82, 130] }
      });

      currentY = doc.lastAutoTable.finalY + 10;
    }

    doc.setFont(undefined, 'normal');
    doc.setFontSize(8);
    doc.text('Generated by PLANORA - Smart Urban Event Governance Platform', 14, 285);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 14, 290);

    doc.save(`PLANORA-Event-Report-${report.event.name.replace(/\s+/g, '-')}.pdf`);
  };

  if (loading) {
    return (
      <div className="event-report-page">
        <div className="loading">Loading report...</div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="event-report-page">
        <div className="error-message">
          {error || 'Event not found'}
        </div>
        <Link to="/municipal-dashboard" className="back-btn">
          Back to Dashboard
        </Link>
      </div>
    );
  }

  return (
    <div className="event-report-page">
      <div className="report-header">
        <h1>Event Coordination Report</h1>
        <div className="report-actions">
          <button onClick={exportPDF} className="export-btn">
            📄 Export as PDF
          </button>
          <Link to="/municipal-dashboard" className="back-btn">
            Back to Dashboard
          </Link>
        </div>
      </div>

      <div className="report-container">
        <section className="report-section">
          <h2>Event Information</h2>
          <div className="info-grid">
            <div className="info-item">
              <span className="info-label">Event Name:</span>
              <span className="info-value">{report.event.name}</span>
            </div>
            <div className="info-item">
              <span className="info-label">Location:</span>
              <span className="info-value">{report.event.location}</span>
            </div>
            <div className="info-item">
              <span className="info-label">Venue Size:</span>
              <span className="info-value">{report.event.venue_size}</span>
            </div>
            <div className="info-item">
              <span className="info-label">Event Type:</span>
              <span className="info-value event-type">
                {report.event.event_type.charAt(0).toUpperCase() + report.event.event_type.slice(1)}
              </span>
            </div>
            <div className="info-item">
              <span className="info-label">Expected Attendees:</span>
              <span className="info-value attendees">
                {report.event.expected_attendees.toLocaleString()}
              </span>
            </div>
            <div className="info-item">
              <span className="info-label">Status:</span>
              <span className={`status-badge ${report.event.status}`}>
                {report.event.status.charAt(0).toUpperCase() + report.event.status.slice(1)}
              </span>
            </div>
          </div>
        </section>

        <section className="report-section">
          <h2>Event Schedule</h2>
          <div className="schedule-box">
            <div className="schedule-item">
              <div className="schedule-icon">🕐</div>
              <div>
                <div className="schedule-label">Start</div>
                <div className="schedule-date">{formatDate(report.event.start_date)}</div>
                <div className="schedule-time">{formatTime(report.event.start_date)}</div>
              </div>
            </div>
            <div className="schedule-divider">→</div>
            <div className="schedule-item">
              <div className="schedule-icon">🕐</div>
              <div>
                <div className="schedule-label">End</div>
                <div className="schedule-date">{formatDate(report.event.end_date)}</div>
                <div className="schedule-time">{formatTime(report.event.end_date)}</div>
              </div>
            </div>
          </div>
          <div className="duration-box">
            <strong>Duration:</strong> {report.summary.eventDuration}
          </div>
        </section>

        <section className="report-section highlight-section">
          <h2>Waste Management Planning</h2>
          <div className="waste-box">
            <div className="waste-icon">♻️</div>
            <div className="waste-content">
              <div className="waste-value">{Math.round(report.event.estimated_waste)} kg</div>
              <div className="waste-label">Estimated Waste Generation</div>
              <p className="waste-note">
                Based on AI prediction model using event type, attendees, and catering scale
              </p>
            </div>
          </div>
        </section>

        {report.vendors && report.vendors.length > 0 && (
          <section className="report-section">
            <h2>Registered Vendors ({report.vendors.length})</h2>
            <div className="vendors-list">
              {report.vendors.map((vendor, index) => (
                <div key={index} className="vendor-item">
                  <div className="vendor-header">
                    <h4>{vendor.name}</h4>
                    <span className="vendor-category">
                      {vendor.category.charAt(0).toUpperCase() + vendor.category.slice(1)}
                    </span>
                  </div>
                  <div className="vendor-contacts">
                    <div>📧 {vendor.contact_email}</div>
                    <div>📞 {vendor.contact_phone}</div>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        <section className="report-section">
          <h2>Summary</h2>
          <div className="summary-grid">
            <div className="summary-card">
              <div className="summary-icon">👥</div>
              <div className="summary-value">{report.summary.totalAttendees.toLocaleString()}</div>
              <div className="summary-label">Total Attendees</div>
            </div>
            <div className="summary-card">
              <div className="summary-icon">🏪</div>
              <div className="summary-value">{report.summary.vendorCount}</div>
              <div className="summary-label">Vendors Hired</div>
            </div>
            <div className="summary-card">
              <div className="summary-icon">♻️</div>
              <div className="summary-value">{Math.round(report.summary.estimatedWaste)} kg</div>
              <div className="summary-label">Est. Waste</div>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}

export default EventReportPage;
